name: Github Actions Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package
      
    - name: Test code
      run: mvn test
    
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/*.jar

    

  Publish-artifact-build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Add JAR File
      uses: actions/download-artifact@v1
      with:
        name: artifact
        path: ./
    
    - name: Docker Image build
      run: docker image build -t java-example:latest . 

  AWS-ECR-Login:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: AWS credentials setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2
     
