name: Github Actions Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install
      
    - name: Test code
      run: mvn test

  Docker-build-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

   
    - name: Docker Image build
      run: docker image build -t java-example:latest .  
