name: Github Actions Task

on: push

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: | 
        mvn clean package
        ls ./target
      
    - name: Test code
      run: mvn test
    
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/*.jar

    

  Publish-artifact-build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Add JAR File
      uses: actions/download-artifact@v1
      with:
        name: artifact
        path: ./
    
    - name: Docker Image build
      run: docker image build -t java-example:latest . 

  AWS-ECR-Login:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: AWS credentials setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2
     
   
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{secrets.REPO_NAME}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
on:
